### ISSUE TITLE
=head1 text should be in UPPER CASE

### ISSUE THREAD

**Issue by neilb** [ThePerlShop/text-diff-html#1]
Hi,

The convention is that `=head1` lines in pod should have upper case text, like:

```
=head1 NAME
=head1 SYNOPSIS
=head1 DESCRIPTION
```

Because they're in mixed case, it looks like MetaCPAN isn't seeing them, so the module doesn't appear like other modules in search results.

This is a nice easy fix, so maybe you could let this stand, and if someone gets this module in the Pull Request challenge, there's one easy thing for them to do :-)

Cheers,
Neil

PS I'll be submitting a bug on MetaCPAN too :-)

**Comment by theory** [comment]
Just No. I have argued this for _years._ =head1 should be cased appropriately as determined by the author. Formatters should change the case as appropriate for their formats, e.g., uppercase for Man pages, original casing for HTML. I've used appropriate casing for my headers for around 10 years, and have sent patches to fix modules unaware of that (e.g., Module::Build) and, [more recently, Pod::Weaver](https://github.com/rjbs/Pod-Weaver/pull/34).
